// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz3GVK7Qpa2WiGmxNAAdNObGMnFGELoo8',
    appId: '1:486814867638:web:99e911178be4224dab4617',
    messagingSenderId: '486814867638',
    projectId: 'asdasf-b2f36',
    authDomain: 'asdasf-b2f36.firebaseapp.com',
    storageBucket: 'asdasf-b2f36.appspot.com',
    measurementId: 'G-PP8GHGBQB5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0y9zXC-pzJ1ZBdayz4rhaocT3rZKDkQk',
    appId: '1:486814867638:android:c5d02b65fa36c601ab4617',
    messagingSenderId: '486814867638',
    projectId: 'asdasf-b2f36',
    storageBucket: 'asdasf-b2f36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSSFab1MQkRtSqd-z9SMem2yoPCK-ZxjI',
    appId: '1:486814867638:ios:16069f456a40b8a2ab4617',
    messagingSenderId: '486814867638',
    projectId: 'asdasf-b2f36',
    storageBucket: 'asdasf-b2f36.appspot.com',
    iosClientId: '486814867638-fm0ml15bt96vi1k2ees7qgp5t667b234.apps.googleusercontent.com',
    iosBundleId: 'com.example.meet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSSFab1MQkRtSqd-z9SMem2yoPCK-ZxjI',
    appId: '1:486814867638:ios:7c62dd1362456c2bab4617',
    messagingSenderId: '486814867638',
    projectId: 'asdasf-b2f36',
    storageBucket: 'asdasf-b2f36.appspot.com',
    iosClientId: '486814867638-voe0i795p0ktic03ccstnng01cn1gq2q.apps.googleusercontent.com',
    iosBundleId: 'com.example.meet.RunnerTests',
  );
}
